# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lazy Mining' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lazy Mining
  pod 'Alamofire', '~> 4.7'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Branch'

  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  target 'Lazy MiningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lazy MiningUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
